services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - parser

  parser:
    build: ./parser
    ports:
      - "4000:4000"
    volumes:
      - ./parser:/app
